Add UITest
NIFCLOUD-mbaas/AndroidSegmentPushApp pull request #7
Opened 2021-02-26 10:04 UTC by vfa-tamhh

+ Upgrade NCMB SDK to 4.0.0
+ Enable Android X
+ Add UI Test

2021-03-03 07:21 UTC, vfaHungnv approved these changes
Code ok.

2021-03-19 02:52 UTC, vfaHungnv requested changes

2021-03-19 02:52 UTC, vfaHungnv commented on app/src/androidTest/java/mbaas/com/nifcloud/androidsegmentpushapp/Utils.java
> +                try {
Mình push theo token rồi nên đk target hơi dư á em.

2021-03-19 03:19 UTC, vfaHungnv approved these changes

2021-04-07 08:35 UTC, kobo0908 approved these changes
こちら問題ありませんのでmergeします。

2021-04-07 08:41 UTC, merged